### ISSUE TITLE
Webview inside sliding view

### ISSUE THREAD

**Issue by mikuke** [hoomazoid/CTSlidingUpPanel#10]
I need to use webview inside sliding view, but the scrollable content out of the parentviews bounds is not drawn.
To fix that I guess the solution is to access the slider scrollview delegate and force webview to redraw itself. 
How can I access scrollview to delegate it's methods to my viewcontroller or do you know any other fix for the issue?

**Comment by mikuke** [comment]
Seems to be issue of html.

**Comment by andriadze** [comment]
Also, just in case make sure that sliding controller is not resizing your webview. This will happen if you improperly implemented bottom constraint
