### ISSUE TITLE
If I use two Slide Up Views . How can I diffrenciate them in delegate methods ??

### ISSUE THREAD

**Issue by rajeshsonu** [hoomazoid/CTSlidingUpPanel#12]
You can ask pretty much anything regarding this library. I will try to answer as quick as I can.

Please while creating a new issue try to be as specific as possible. Describe issue as best as you can. 
If applicable, please provide code of what is not working properly.

**Comment by andriadze** [comment]
Sadly, that's not yet possible. 

I will try to put it in the next update

**Comment by rajeshsonu** [comment]
Thanks for support

**Comment by andriadze** [comment]
I know this is late, but it's done I think. I have added closures.

Do pod update, you should get version 1.0.4

Here they are:

```swift
 bottomController?.onPanelExpanded = {
      print("Panel Expanded in closure")
 }
        
 bottomController?.onPanelCollapsed = {
      print("Panel Collapsed in closure")
 }
        
 bottomController?.onPanelAnchored = {
      print("On Panel anchored")
 }
        
 bottomController?.onPanelMoved = { offset in
      print("Panel moved in closure " + offset.description)
 }
```
