### ISSUE TITLE
Panel sliding too high

### ISSUE THREAD

**Issue by keithburgoyne** [hoomazoid/CTSlidingUpPanel#16]
Hi there!

I have a basic UIViewController embedded in a UINavigationController, in turn embedded in a UITabBarController. The siding panel is displaying correctly above the tab bar.

However, when I expand the panel, it slides up under the top navigation bar. I'd like it to stop once it reached the bottom of the bar.

I've confirmed that the panel's parent view does not extend beyond the top nav bar (I have the options "Under Bottom Bars," and "Under Top Bars" disabled in the "Extend Edges" section of interface builder). Looking at the exploded view in the interface debugger shows the parent view, which is the main view in the controller, does not extend above the nav bar, yet it shows that the panel does.

Any help you could provide would be great!

**Comment by keithburgoyne** [comment]
If I set the `expandedTopMargin` value to the height of the nav bar and test with that, I can't drag the panel up past the top bar. But if I let go of the panel, it slides right back up to the top.

It actually looks like the panel's height is equal to the parent's height, plus the tab bar's height.

**Comment by andriadze** [comment]
Hi, I am not near my computer right now. I will check out your issue on
Monday

**Comment by keithburgoyne** [comment]
Thanks!

**Comment by andriadze** [comment]
Hi, can you confirm that you've correctly provided navigation controller to the Sliding controller initializer? 

Also can you tell me which constraints are set on sliding view?

**Comment by keithburgoyne** [comment]
Hi there,

Sorry my reply is so late. On the sliding view, there are two UILabels. The following constraints are enabled:

```
label1.top = top + 10
label1.centerX = centerX
label2.centerY = centerY
label2.centerX = centerX
```

I am getting the navigation and tabbar controllers by calling `self.navigationController` and `self.tabBarController` in the parent view controller before passing them to the `CTBottomSlideController`.

I am setting up the panel in the parent view controller's viewDidLoad() function. 

There are no further constraints on the view.

**Comment by keithburgoyne** [comment]
I have found the issue. By default, my parent UIViewControllers did not have `Extend Edges Under Opaque Bars` checked. My tab bar is indeed opaque, so the parent view was being sized such that its bottom edge was equal to the top edge of the tab bar. This is why the sliding panel would slide up too high -- it's starting position was the bottom of the parent view, as expected.

Clicking `Extend Edges Under Opaque Bars` solved my problem.

Thanks for taking the time to follow up with this issue!

**Comment by andriadze** [comment]
Glad you solved the problem I was kinda lost with this 😃
