### ISSUE TITLE
how to change the content of the bottomView which is going to slide up and down

### ISSUE THREAD

**Issue by sunflower860726** [hoomazoid/CTSlidingUpPanel#17]
My problem is that I am going to move and resize the content view of the controller that is embedded in bottomView.
You can see my idea in youtube app.
How can I know do that?

**Comment by andriadze** [comment]
Hi, what you can do is wrap sliding view in another view and provide that wrapper view as bottom view to SlidingUpController. Afterwards you can add or remove any view into that wrapper view for as long as you don't change the wrapper itself.

**Comment by andriadze** [comment]
Assuming you fixed the problem.
