### ISSUE TITLE
Sliding Panel + Embeded Container View + Scroll View

### ISSUE THREAD

**Issue by muzammilsahib** [hoomazoid/CTSlidingUpPanel#19]
Please provide some samples how to use scroll view in slide panel, how to use top constraints. 

the issue is when I move the slide panel up, it is went into the full screen then it cannot be moved down.

thanks

**Comment by muzammilsahib** [comment]
In addition to that how can I reset the sliding panel back to normal position (ie. open from Bottom view as an visible height)

**Comment by muzammilsahib** [comment]
Hi, this is resolved I found the issue and solution.

thanks

**Comment by SethArchambault** [comment]
@muzammilsahib Any details or examples as to how you achieved this?
