### ISSUE TITLE
Fatal error: initialTouchLocation = nil

### ISSUE THREAD

**Issue by relaxsus** [hoomazoid/CTSlidingUpPanel#20]
When I pull up in CTBottomSlideController on 301 lines an error: "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value". 

What could be the problem?

**Comment by andriadze** [comment]
Does it keep happening or was that a one time thing?

**Comment by relaxsus** [comment]
The problem is not stable, I do not see the logic, but it repeats periodically

**Comment by relaxsus** [comment]
This happens if one of the species is out of bounds bottomView and if you try to pull this view

**Comment by keithburgoyne** [comment]
I'm seeing this issue too. I'll post when I get some further details.

**Comment by andriadze** [comment]
Give me detailed instructions on how to reproduce the bug and I'll issue an
update within couple of days. Maybe even tomorrow

**Comment by keithburgoyne** [comment]
Looks like line 301 of `CTBottomSlideController.swift`:

`                if(initialTouchLocation - touchLocation.y > 23){`

Will attempt to provide steps to reproduce. I don't get a stack trace.

**Comment by keithburgoyne** [comment]
Here is how I've managed to reproduce it:

1. Panel must be in the collapsed position. 
2. Click the panel and barely move it up.
3. Release the panel but then instantly click it again. You have to move very quickly.

**Comment by andriadze** [comment]
All right will give it a go in couple of minutes and see what I can do

**Comment by keithburgoyne** [comment]
Many thanks!

**Comment by keithburgoyne** [comment]
For the record, `initialTouchLocation` appears to be `nil` when the crash occurs.

**Comment by keithburgoyne** [comment]
You might be able to reproduce it with lots of rapid clicking on the collapsed panel as well. I've been testing with the iPhone X simulator, if that helps.

**Comment by andriadze** [comment]
Initial touch location was checked for nil only while pan gesture recognizer state was ".changed"

Just commited the fix will push to pod now

**Comment by andriadze** [comment]
Okay, done do the pod update. 

You should get version 1.0.5. Please check and report back

**Comment by keithburgoyne** [comment]
Looks like it's fixed for me! Thanks!

**Comment by relaxsus** [comment]
Perfectly! The problem is fixed! Thank you very much for your efforts!

**Comment by nivol05** [comment]
why fore me this problem not fix??

**Comment by andriadze** [comment]
Maybe you did not do the pod update before eunning pod install and it installed the precious version of the library.

Please try and notify me. After doing this If necessary please open up a new issue.

**Comment by nivol05** [comment]
I just made the manual installation and the problem disappeared
Thx for feedback)

**Comment by nivol05** [comment]
Because if installation you staff using pod file installing old version

**Comment by andriadze** [comment]
That's most definitely because you need to run pod update command before
running pod install.
