### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by isaacraja15** [hoomazoid/CTSlidingUpPanel#23]
I just try this method for my application , but i have one issue in  bottomController 
my error is 

bottomController	CTSlidingUpPanel.CTBottomSlideController?	nil	none
this is my code 
import UIKit
import CTSlidingUpPanel
class ViewController: UIViewController, CTBottomSlideDelegate {
   
    @IBOutlet weak var bottomView: UIView!
    var bottomController:CTBottomSlideController?
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        bottomController = CTBottomSlideController(parent: view, bottomView: bottomView, tabController: self.tabBarController!, navController: self.navigationController, visibleHeight: 64)
        
        
        bottomController?.setAnchorPoint(anchor: 0.7)
        bottomController?.delegate = self;
        
        bottomController?.onPanelExpanded = {
            print("Panel Expanded in closure")
        }
        
        bottomController?.onPanelCollapsed = {
            print("Panel Collapsed in closure")
        }
        
        bottomController?.onPanelMoved = { offset in
            print("Panel moved in closure " + offset.description)
        }
        
        //Uncomment to specify top margin on expanded panel
        //bottomController?.setExpandedTopMargin(pixels: 100)
        
        if bottomController?.currentState == .collapsed
        {
            //do anything, i don't care
        }
    }
    
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        bottomController?.viewWillTransition(to: size, with: coordinator)
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func didPanelCollapse()
    {
        print("Collapsed");
    }
    func didPanelExpand(){
        print("Expanded")
    }
    func didPanelAnchor(){
        print("Anchored")
    }
    
    func didPanelMove(panelOffset: CGFloat)
    {
        print(panelOffset);
    }
    
    
}

How can i solve this

**Comment by andriadze** [comment]
Make sure view, bottomView, tabBarController, navigationController are not nil

**Comment by isaacraja15** [comment]
im not you tabbar i just try Slideup panel .
here bottomviewcontroller is nil
how can i solve it ?

**Comment by andriadze** [comment]
I really don't get what you mean

**Comment by isaacraja15** [comment]
i attached my file im using CTSlidingup panel pod but its not work

bottomController CTSlidingUpPanel.CTBottomSlideController? nil

**Comment by andriadze** [comment]
Are you using TabBarController in your view?

**Comment by isaacraja15** [comment]
No.

**Comment by andriadze** [comment]
Use "nil" instead of "self.tabBarController" in the initializer.

Also, you really need to read some more about Swift

**Comment by isaacraja15** [comment]
yes, Basically im web developer, I have 5 years experience in web platform. now im move to app development. so i have 2 months experience in swift. so i need some help to learn SWIFT
