### ISSUE TITLE
Sliding Panel + TableView

### ISSUE THREAD

**Issue by Tomsky7Summits** [hoomazoid/CTSlidingUpPanel#26]
Hi,

I subclassed the "Pull this up or down" view controller and added a table view below the "Pull this up or down" label. How can I set the table view using the public func set(table:UITableView) of the slide controller?

Thank you very much

**Comment by andriadze** [comment]
Create an outlet, afterwards use set(table:UITableView).

There are 2 ViewControllers in example one of them has tableview
