### ISSUE TITLE
Can i add tableview instead of UIView ?

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [hoomazoid/CTSlidingUpPanel#3]
@hoomazoid , Thanks for great library. Shall i add tableview instead of UIVIew.  I need to display tableview.

**Comment by andriadze** [comment]
Hi you can provide any view to the bottom panel. Anything that extends UIView (Tableview, UISubview, UIButton, UITextfield, UILabel). If this does not work just wrap your tableview in generic UIView and then provide that to the sliding panel.


While initializing CTBottomSlideController privde tableview to bottomView - parameter
```Swift
 bottomController = CTBottomSlideController(parent: view, bottomView: tableView, 
                        tabController: self.tabBarController!,
                        navController: self.navigationController, visibleHeight: 64)
```

After that if you want sliding panel to slide depending on scroll offset of tableview you should do this: 
```
bottomController.set(table:tableView)
