### ISSUE TITLE
Is it support Objc project?

### ISSUE THREAD

**Issue by poloteh** [hoomazoid/CTSlidingUpPanel#30]
You can ask pretty much anything regarding this library. I will try to answer as quick as I can.

Please while creating a new issue try to be as specific as possible. Describe issue as best as you can. 
If applicable, please provide code of what is not working properly.

**Comment by andriadze** [comment]
Hi, I think you will be able to use it in an Objective C project. I have not tested it and I don't have any examples for it though.

If you test it and works please notify me.

**Comment by poloteh** [comment]
I have tested it, the swift Function is not shown in objective-C project. Just want to confirm.

**Comment by andriadze** [comment]
Just tried it in a test objective c project and the lib works with some minor changes.

First of all you have to use: `use_frameworks!` in you podfile and run pod install afterwards.

After this you have to build your project and you can import library in Objective C file like this: 
`@import CTSlidingUpPanel;`

Now here comes the issue. For necessary methods to be seen in Objective C, you have to manually add `@objc` tag in front of method declaration in Pods swift file like so:

`@objc public init(parent: UIView, bottomView: UIView, tabController:UITabBarController?, navController:UINavigationController?, visibleHeight: CGFloat)` 

After you do this methods annotated with `@objc` will become visible to objective c:
`controller = [[CTBottomSlideController alloc] initWithParent:self.view bottomView:_testView tabController:nil navController:nil visibleHeight:20];`

**Comment by andriadze** [comment]
I will add these annotations in the next build(After testing in both Swift and Obj C projects). Meanwhile you can add those yourself, test it and hit me up with a pull request.

**Comment by poloteh** [comment]
Actually, I have tried some of the solutions, it not working properrly. But you just have to add @objcMembers before class. Then it should settle everything
![Screenshot 2019-03-13 at 3 20 34 PM](https://user-images.githubusercontent.com/12995269/54263575-1de8d380-45ac-11e9-88e6-b71f22e3c8f7.png)

**Comment by andriadze** [comment]
Thanks for PR, releasing new version to pods(Version 1.2.0).
Be sure to test as good as you can and if something notify me.
