### ISSUE TITLE
want to set the height of bottomController as per embedded content view's Height. 

### ISSUE THREAD

**Issue by bhavipandit16** [hoomazoid/CTSlidingUpPanel#33]
Hello,

I set tableview as content view in bottomController, I want to set dynamic height of bottomController cause data comes 2 or more than that. if two data comes then slider should not slide and if more than 2 comes then it should slide.

need help.

Thanks.

**Comment by andriadze** [comment]
There are couple of options:
1. You can wrap your bottom view in another view and use that as a parent(See safe area support part of the ReadMe).
2. You can use `setExpandedTopMargin(pixels: CGFloat)` in combination of some other constrains. And just disable sliding when not necessary `setSlideEnabled(bool)`

**Comment by bhavipandit16** [comment]
Hello,

I did that but sliding view is not resize as per the content view.

Please check the below image if there is two row then sliding resize as per that which are not resizing. I applied #1 option.

Please suggest me.

Thanks.

![1](https://user-images.githubusercontent.com/45426016/54429650-245f8280-4747-11e9-8dea-6738a8d60b3a.png)
![2](https://user-images.githubusercontent.com/45426016/54429651-24f81900-4747-11e9-8b69-36ea44ace88a.png)

**Comment by andriadze** [comment]
You can try experimenting with different constraints and changing different parameters of the library. 
Sorry, but I can't exactly tell you how to do it.
