### ISSUE TITLE
Controller not respecting top and height constraints

### ISSUE THREAD

**Issue by jbart12** [hoomazoid/CTSlidingUpPanel#37]
Thanks for the library.  I'm using it in two area of my app.  The first is working perfectly, the second is not respecting the top/height constraints.  In my view controller I have added a view and set the left, right, top, and height constraints (not bottom).  Height constraint is set to 400.  Top is set to master view top + 100 (master view top is safe area).

I reference the view and it's constraints with:

```
@IBOutlet var bottomView: UIView!
@IBOutlet var topConstraint: NSLayoutConstraint!
@IBOutlet var heightConstraint: NSLayoutConstraint!

```

Then I init the bottomController with:

`bottomController = CTBottomSlideController(topConstraint: topConstraint, heightConstraint: heightConstraint, parent: view, bottomView: bottomView, tabController: nil, navController: nil, visibleHeight: 250)`

but the view still opens all the way to top of screen.  Any help is appreciated!

**Comment by andriadze** [comment]
Hi, I'm not with the computer right now so can't give you detailed answer quickly. But there are 2 ways of doing what you are trying to achieve: 

1. Check setExpandedTopMargin in the readme.
2. If above does not work for you check out iphone x safe area support section and following that give the wrapper view whatever constraints you want.

If neither works for you let me know and I'll give you more detailed answer a bit later

**Comment by andriadze** [comment]
Any updates? 

I'll be closing the issue by tomorrow
