### ISSUE TITLE
CTSlidingUpPanel over MapView question...

### ISSUE THREAD

**Issue by LilMoke** [hoomazoid/CTSlidingUpPanel#38]
Hello,

I was wondering if you have had any issues with a CTSlidingUpPanel over a MapView?

I have a ViewController with a MKMapView.  In ViewDidLoad I am creating a CTSlidingUpPanel, but when the map is done rendering any touches not the CTSlidingUpPanel moves the map and thus does not allow the panel to be pulled up.

I know this is slightly old, but if you have any idea why I may be having this issue I wold appreciate it.

**Comment by andriadze** [comment]
Hi, my main usage with this library was actually was with Google Maps and I never encountered such issue. Can you give me any code example or screenshot of how specifically your view is set up?

**Comment by LilMoke** [comment]
Thank you for the speedy reply.  Actually just by telling me it is supposed to work you have helped me.  I thought it was because of something I was doing.  I will look at my code now that I feel confident it is me and if I have any Issues I will gladly send you a sample.  -:)

Thank you again.

**Comment by LilMoke** [comment]
andriadze, I have located my issue.  It turned out that I did not have trailing and leading constraints on my parent view.  Once I added those two constraints everything worked as expected.  My bad... thanks for your help though!!!  Stay safe!

**Comment by LilMoke** [comment]
Giorgi,

Everything works great.  One question... is there a way to completely hide the panel?  I called hidPanel, but it it looks like hide and close do the same thing.

I was assuming that hide would hide it completely and then calling collapse or expand would show the plane again in the deserted state.

I look at the code and both hide and close appear to do the same thing.  Is that the intended behavior or is it a potential issue?

Thank you

**Comment by andriadze** [comment]
Hi, no hide is supposed to completely hide it. there is 1 line difference in code. It might have something to do with your layout setup. Can you please try hidePanel with example code and see if it works there?

**Comment by jesuasir007** [comment]
Thanks for quick reply andriadze ,

please give me the more detail about the slide up functions and creating a view without tap bar and navigation bar.

**Comment by jesuasir007** [comment]
detailed documentation about the functions 

.collapsed
.expanded
.anchored
.hidden

and

        bottomController = CTBottomSlideController(parent: view, bottomView: bottomView, tabController: nil, navController: nil, visibleHeight: 120)
        bottomController?.setAnchorPoint(anchor: 0)
        bottomController?.delegate = self;
        bottomController?.onPanelExpanded = {
            print("Panel Expanded in closure")
        }
        
        bottomController?.onPanelCollapsed = {
            print("Panel Collapsed in closure")
        }
        
        bottomController?.onPanelMoved = { offset in
            print("Panel moved in closure " + offset.description)
        }
        if bottomController?.currentState == .collapsed
        {
            //do anything, i don't care
        }

**Comment by jesuasir007** [comment]
working fine today I have fix it ,thank you lot .

**Comment by andriadze** [comment]
Okay in that case closing the issue
