### ISSUE TITLE
Maximum height?

### ISSUE THREAD

**Issue by daerimin** [hoomazoid/CTSlidingUpPanel#6]
Hi there!  Thank you very much for the library!  It's a near-perfect fit for my project.  I'd like to ask if there's a way to limit the height that the view can expand to.

**Comment by andriadze** [comment]
Hmm, right now I don't think that's possible. But it should be quite an easy change. Will look into it

**Comment by andriadze** [comment]
Consider it done releasing new version to cocoapods.

Do a **pod update** 
New version should be: 1.0.3

**Comment by daerimin** [comment]
Thank you very much for your efforts.  I appreciate your fast response.  At present, I still do not see any way to set a maximum height for the bottom view.  Could you please tell me how to do that?

Thank you again!!!

**Comment by andriadze** [comment]
Oh right, so there's new method.

You can specify "Top constraint" in pixels. Like you can do:
```
bottomController?.setExpandedTopMargin(pixels: 100)
```

**Comment by andriadze** [comment]
Okay I am assuming that this fixed your issue.

**Comment by daerimin** [comment]
Thank you very much for your work - I appreciate it.  Unfortunately a top margin does not help me, as it does not restrict the height of the bottom view.

**Comment by andriadze** [comment]
Well the thing is. Sliding view takes up the height of it's parent view. You can wrap sliding view in a generic UIView and provide that as a parent argument to the initializer of bottom controller.

You can give that wrapper view any constraint you want. Check out Iphone X support part of the README to better understand what I mean

**Comment by andriadze** [comment]
Glad to help. Please tell me if it worked.
