### ISSUE TITLE
Add bottom margin/padding to sliding view

### ISSUE THREAD

**Issue by mikuke** [hoomazoid/CTSlidingUpPanel#8]
Hi,

I want to have the slider starting from 128px above the bottom line of the screen. 
Another option is to position the sliding view above another view but as constraint's are not allowed, I can't do that. 

My slider's visible height is always 0 and I'm using WKWebView as the slider content.
I will control slider closing/hiding always from code. 
Bottom of the slider view should be another view's top (slider is behind that view) or 128 pixels from bottom of the screen (it's the height of that "another view")

**Comment by andriadze** [comment]
Hi, use solution mentioned in this answer:
https://github.com/hoomazoid/CTSlidingUpPanel/issues/4#issuecomment-357503732

It's for iPhone X safe area support, but it will most def work for your problem

**Comment by mikuke** [comment]
Thanks, I actually figured same solution out by myself. :)
